#!/bin/bash

if [ -z "$1" ]
  then
    echo "You must pass the VM name as the 1st argument"
fi
if [ -z "$2" ]
  then
    echo "You must pass the snapshot name as the 2nd argument"
fi

NAME=$1
SNAPSHOT=$2
vboxmanage snapshot $NAME restore $SNAPSHOT
