#!/bin/bash

NAME="$1"
VBOX="/usr/bin/VBoxManage"

if [ $# -ne 1 ]; then
  echo "Usage: vbox-restore-clean <vm name>"
  exit
fi

$VBOX controlvm "$NAME" poweroff || echo "Failed to poweroff vm"
$VBOX snapshot "$NAME" restore "clean" || echo "Failed to restore snapshot"

echo "Restored $1 to clean"
